-- drop table extension

 IF NOT EXISTS (SELECT 1 FROM SYS.tables where name='EXTENSION')
 BEGIN
	CREATE TABLE [dbo].[EXTENSION](
		[EXTENSIONID] [int] IDENTITY(1,1) NOT NULL,
		[EXTENSIONTYPE] [varchar](50) NOT NULL,
		[EXTENSIONCODE] [varchar](50) NOT NULL,
		[EXTENSIONSTATUS] varchar(50) NULL,
		[EXTENSIONPARAM] [nvarchar](max) NULL,
		[EXTENSIONPARAM_HTML] bit NULL,
		[EXTENSIONUSERID] [int] NULL,
		[EXTENSION84] bit NULL,
		[EXTENSION88] varchar(512) NULL,
		[EXTENSION89] varchar(max) NULL,
		[EXTENSION89_HTML] bit NULL,
		[EXTENSION96] [datetime] NULL,
		[EXTENSION95] [datetime] NULL,
		[EXTENSION93] [varchar](max) NULL,
		[EXTENSION93_HTML] bit NULL,
		[EXTENSION94] [varchar](max) NULL,
		[EXTENSION94_HTML] bit NULL,
		[EXTENSION97] [int] NULL,
		[EXTENSION98] [int] NULL,
		[EXTENSIONDATEENABLED] [datetime] NULL,
		[EXTENSIONDATEDISABLED] [datetime] NULL,
		[EXTENSION99] [int] NULL,
	 CONSTRAINT [PK_EXTENSION] PRIMARY KEY CLUSTERED 
	(
		[EXTENSIONID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

END

 
