 
 IF NOT EXISTS (SELECT 1 FROM SYS.indexes where name='IX_CODE' AND  OBJECT_NAME(object_id) = 'EXTENSION')
 BEGIN
	CREATE NONCLUSTERED INDEX [IX_CODE] ON [dbo].[EXTENSION]
	(
		[EXTENSIONTYPE] ASC,
		[EXTENSIONCODE] ASC,
		[EXTENSIONUSERID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
END


