IF NOT EXISTS (
		SELECT 1
		FROM sys.tables
		INNER JOIN syscolumns ON syscolumns.id = sys.tables.object_id
		WHERE sys.tables.name LIKE 'EXTENSION'
			AND syscolumns.name LIKE 'EXTENSIONAUTHENTICATIONTOKEN'
		)
BEGIN
	ALTER TABLE EXTENSION ADD EXTENSIONAUTHENTICATIONTOKEN VARCHAR(500)
END


INSERT INTO [DESC](DescId, [File], Field, Format, Length)
SELECT 101111, 'EXTENSION', 'EXTENSIONAUTHENTICATIONTOKEN', 1, 255
WHERE NOT EXISTS (
	SELECT DescId FROM [DESC] WHERE DescId = 101111
)

INSERT INTO [RES](ResId, LANG_00)
SELECT 101111, 'EXTENSIONAUTHENTICATIONTOKEN'
WHERE NOT EXISTS (
	SELECT ResId FROM [RES] WHERE ResId = 101111
)
