 
IF EXISTS (SELECT * FROM sys.indexes WHERE name='IX_CODE_STATUS' AND object_id = OBJECT_ID('[EXTENSION]'))
	DROP INDEX [IX_CODE_STATUS] ON [dbo].[EXTENSION]


/****** Object:  Index [IX_CODE_STATUS]    Script Date: 22/01/2019 14:52:59 ******/
CREATE NONCLUSTERED INDEX [IX_CODE_STATUS] ON [dbo].[EXTENSION]
(
	[EXTENSIONCODE] ASC,
	[EXTENSIONSTATUS] ASC
)
INCLUDE ( 	[EXTENSIONACTIVATIONKEY]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
 


