update RES
	set 
		LANG_00 = (SELECT TOP 1 LANG FROM EUDORES..RESAPP WHERE ResId = 389 AND Id_Lang = 0 ),
		LANG_01 = (SELECT TOP 1 LANG FROM EUDORES..RESAPP WHERE ResId = 389 AND Id_Lang = 1 ),
		LANG_02 = (SELECT TOP 1 LANG FROM EUDORES..RESAPP WHERE ResId = 389 AND Id_Lang = 2 ),
		LANG_03 = (SELECT TOP 1 LANG FROM EUDORES..RESAPP WHERE ResId = 389 AND Id_Lang = 3 ),
		LANG_04 = (SELECT TOP 1 LANG FROM EUDORES..RESAPP WHERE ResId = 389 AND Id_Lang = 4 ),
		LANG_05 = (SELECT TOP 1 LANG FROM EUDORES..RESAPP WHERE ResId = 389 AND Id_Lang = 5 ),
		LANG_06 = (SELECT TOP 1 LANG FROM EUDORES..RESAPP WHERE ResId = 389 AND Id_Lang = 6 ),
		LANG_07 = (SELECT TOP 1 LANG FROM EUDORES..RESAPP WHERE ResId = 389 AND Id_Lang = 7 ),
		LANG_08 = (SELECT TOP 1 LANG FROM EUDORES..RESAPP WHERE ResId = 389 AND Id_Lang = 8 ),
		LANG_09 = (SELECT TOP 1 LANG FROM EUDORES..RESAPP WHERE ResId = 389 AND Id_Lang = 9 )

FROM RES R
WHERE ResId in (
SELECT [descid] + 4 FROM [DESC] WHERE [Type] = 4
)

update RES
	set 
		LANG_00 = (SELECT TOP 1 LANG FROM EUDORES..RESAPP WHERE ResId = 383 AND Id_Lang = 0 ),
		LANG_01 = (SELECT TOP 1 LANG FROM EUDORES..RESAPP WHERE ResId = 383 AND Id_Lang = 1 ),
		LANG_02 = (SELECT TOP 1 LANG FROM EUDORES..RESAPP WHERE ResId = 383 AND Id_Lang = 2 ),
		LANG_03 = (SELECT TOP 1 LANG FROM EUDORES..RESAPP WHERE ResId = 383 AND Id_Lang = 3 ),
		LANG_04 = (SELECT TOP 1 LANG FROM EUDORES..RESAPP WHERE ResId = 383 AND Id_Lang = 4 ),
		LANG_05 = (SELECT TOP 1 LANG FROM EUDORES..RESAPP WHERE ResId = 383 AND Id_Lang = 5 ),
		LANG_06 = (SELECT TOP 1 LANG FROM EUDORES..RESAPP WHERE ResId = 383 AND Id_Lang = 6 ),
		LANG_07 = (SELECT TOP 1 LANG FROM EUDORES..RESAPP WHERE ResId = 383 AND Id_Lang = 7 ),
		LANG_08 = (SELECT TOP 1 LANG FROM EUDORES..RESAPP WHERE ResId = 383 AND Id_Lang = 8 ),
		LANG_09 = (SELECT TOP 1 LANG FROM EUDORES..RESAPP WHERE ResId = 383 AND Id_Lang = 9 )

FROM RES R
WHERE ResId in (
SELECT [descid] + 8 FROM [DESC] WHERE [Type] = 4
)
