IF NOT EXISTS (
  SELECT * 
  FROM   sys.columns 
  WHERE  object_id = OBJECT_ID(N'[dbo].[CAMPAIGNSTATSADV]') 
         AND name = 'CAMPAIGNSTATSADV19'
)
BEGIN
	ALTER TABLE CAMPAIGNSTATSADV ADD CAMPAIGNSTATSADV19 NUMERIC(18,0) default(0)
END
