DECLARE @tabName VARCHAR(100) ;
DECLARE @columnName VARCHAR(100);
DECLARE @nbTab INT ;
DECLARE @idDesc INT;
DECLARE @idSubject INT;

SET @nbTab = 106000;
SET @idSubject = 106005;
SET @idDesc = 106045;
SET @columnName = 'SubjectInClear';
SET @tabName = 'CAMPAIGN';

IF (EXISTS (SELECT * 
                 FROM sys.tables 
                 WHERE  name = @tabName))
BEGIN
    IF (NOT EXISTS (SELECT * 
                 FROM sys.columns
                 WHERE object_id = OBJECT_ID(N'[dbo].'+@tabName) 
                  AND name = @columnName))
		BEGIN
			ALTER TABLE dbo.CAMPAIGN
			ADD SubjectInClear nvarchar(max) NULL;
		END
		
END
ELSE
RETURN;

/*
if EXISTS (SELECT DESCID FROM [DESC] WHERE DESCID = (@idDesc -1) and [Field] =@columnName) 
BEGIN
DELETE FROM [DESC] WHERE DescId = (@idDesc -1) 
--DELETE FROM [RES] WHERE ResId = (@idDesc -1)
END
if EXISTS (SELECT RESID FROM [RES] WHERE RESID = (@idDesc -1) and [LANG_00] ='Objet') 
BEGIN
DELETE FROM [RES] WHERE ResId = (@idDesc -1)
END
*/

IF NOT EXISTS (SELECT DESCID FROM [DESC] WHERE DESCID = @idDesc and [Field] =@columnName)
BEGIN
INSERT INTO [dbo].[DESC]
           ([DESCID],
           [File]
           ,[Field]
           ,[Format]
           ,[Length]
           ,[Case]
           ,[ToolTipText]
           ,[Formula]
           ,[Default]
           ,[Historic]
           ,[Obligat]
           ,[Multiple]
           ,[Popup]
           ,[PopupDescId]
           ,[BoundDescId]
           ,[ActiveTab]
           ,[ActiveBkmEvent]
           ,[ActiveBkmPp]
           ,[ActiveBkmPm]
           ,[GetLevel]
           ,[ViewLevel]
           ,[UserLevel]
           ,[InterEvent]
           ,[InterPp]
           ,[InterPm]
           ,[Rowspan]
           ,[Colspan]
           ,[DispOrder]
           ,[TabIndex]
           ,[Bold]
           ,[Italic]
           ,[Underline]
           ,[Flat]
           ,[ForeColor]
           ,[AutoBuildName]
           ,[Mask]
           ,[Type]
           ,[InterEventNum]
           ,[DefaultFormat]
           ,[Disabled]
           ,[Columns]
           ,[ExternalDataSource]
           ,[Icon]
           ,[ReadOnly]
           ,[ChangeRulesId]
           ,[AlertEnabled]
           ,[Html]
           ,[RowsBkm]
           ,[AutoSave]
           ,[ViewPermId]
           ,[UpdatePermId]
           ,[BkmViewRulesId_100]
           ,[BkmViewRulesId_200]
           ,[BkmViewRulesId_300]
           ,[ObligatRulesId]
           ,[LabelAlign]
           ,[Relation]
           ,[Storage]
           ,[Unicode]
           ,[Rows]
           ,[NoDefaultClone]
           ,[PagingEnabled]
           ,[BkmAddRulesId_100]
           ,[BkmAddRulesId_200]
           ,[BkmAddRulesId_300]
           ,[NoDefaultLink_100]
           ,[NoDefaultLink_200]
           ,[NoDefaultLink_300]
           ,[DeleteRulesId]
           ,[DefaultLink_100]
           ,[DefaultLink_200]
           ,[DefaultLink_300]
           ,[AutoSelectEnabled]
           ,[AutoSelectValue]
           ,[LeftMenuLinksPermId]
           ,[InterPpNeeded]
           ,[InterPmNeeded]
           ,[BkmInlineModeEnabled]
           ,[NbrBkmInline]
           ,[CountOnDemand]
           ,[TreatmentMaxRows]
           ,[EventAnnexListEnabled]
           ,[PmAnnexListEnabled]
           ,[PpAnnexListEnabled]
           ,[SizeLimit]
           ,[Scrolling]
           ,[RestrictedSearch]
           ,[ColorRulesId]
           ,[ViewRulesId]
           ,[SavePJ2Text]
           ,[InterEventNeeded]
           ,[DraftAutoSaveActive]
           ,[DraftAutoSaveInterval]
           ,[BkmViewPermId_100]
           ,[BkmViewPermId_200]
           ,[BkmViewPermId_300]
           ,[SearchLimit]
           ,[ProspectEnabled]
           ,[SavePJ2TextField]
           ,[BkmPagingMode]
           ,[Parameters]
           ,[AdvancedSearchDescId]
           ,[ComputedColsInList]
           ,[ComputedColsInBkm]
           ,[ComputedFieldEnabled]
           ,[DblWindowDisplayedFields]
           ,[DblWindowShowConfidential]
           ,[DblWindowHideToolTip]
           ,[ActiveScroll]
           ,[DisableGroup]
           ,[DetailBkmBarButtons]
           ,[TreeViewUserList]
           ,[FullUserList]
           ,[BkmAutoLinkPmToPPEnabled]
           ,[ObligatReadOnly]
           ,[DisplayFirstBkmOnly]
           ,[IntellimailEnabled]
           ,[InterEventHidden]
           ,[BreakLine]
           ,[SAVEBKMPAGING]
           ,[SelectionSourceTab]
           ,[NoCascadePPPM]
           ,[NoCascadePMPP]
           ,[AutoCompletion]
           ,[IconColor]
           )

     SELECT @idDesc,
	 [File]
      ,'SubjectInClear'
      ,1
      ,255
      ,[Case]
      ,[ToolTipText]
      ,[Formula]
      ,[Default]
      ,[Historic]
      ,[Obligat]
      ,[Multiple]
      ,[Popup]
      ,[PopupDescId]
      ,[BoundDescId]
      ,[ActiveTab]
      ,[ActiveBkmEvent]
      ,[ActiveBkmPp]
      ,[ActiveBkmPm]
      ,[GetLevel]
      ,[ViewLevel]
      ,[UserLevel]
      ,[InterEvent]
      ,[InterPp]
      ,[InterPm]
      ,[Rowspan]
      ,[Colspan]
      ,[DispOrder]
      ,[TabIndex]
      ,[Bold]
      ,[Italic]
      ,[Underline]
      ,[Flat]
      ,[ForeColor]
      ,[AutoBuildName]
      ,[Mask]
      ,[Type]
      ,[InterEventNum]
      ,[DefaultFormat]
      ,[Disabled]
      ,[Columns]
      ,[ExternalDataSource]
      ,[Icon]
      ,[ReadOnly]
      ,[ChangeRulesId]
      ,[AlertEnabled]
      ,[Html]
      ,[RowsBkm]
      ,[AutoSave]
      ,[ViewPermId]
      ,[UpdatePermId]
      ,[BkmViewRulesId_100]
      ,[BkmViewRulesId_200]
      ,[BkmViewRulesId_300]
      ,[ObligatRulesId]
      ,[LabelAlign]
      ,[Relation]
      ,[Storage]
      ,[Unicode]
      ,[Rows]
      ,[NoDefaultClone]
      ,[PagingEnabled]
      ,[BkmAddRulesId_100]
      ,[BkmAddRulesId_200]
      ,[BkmAddRulesId_300]
      ,[NoDefaultLink_100]
      ,[NoDefaultLink_200]
      ,[NoDefaultLink_300]
      ,[DeleteRulesId]
      ,[DefaultLink_100]
      ,[DefaultLink_200]
      ,[DefaultLink_300]
      ,[AutoSelectEnabled]
      ,[AutoSelectValue]
      ,[LeftMenuLinksPermId]
      ,[InterPpNeeded]
      ,[InterPmNeeded]
      ,[BkmInlineModeEnabled]
      ,[NbrBkmInline]
      ,[CountOnDemand]
      ,[TreatmentMaxRows]
      ,[EventAnnexListEnabled]
      ,[PmAnnexListEnabled]
      ,[PpAnnexListEnabled]
      ,[SizeLimit]
      ,[Scrolling]
      ,[RestrictedSearch]
      ,[ColorRulesId]
      ,[ViewRulesId]
      ,[SavePJ2Text]
      ,[InterEventNeeded]
      ,[DraftAutoSaveActive]
      ,[DraftAutoSaveInterval]
      ,[BkmViewPermId_100]
      ,[BkmViewPermId_200]
      ,[BkmViewPermId_300]
      ,[SearchLimit]
      ,[ProspectEnabled]
      ,[SavePJ2TextField]
      ,[BkmPagingMode]
      ,[Parameters]
      ,[AdvancedSearchDescId]
      ,[ComputedColsInList]
      ,[ComputedColsInBkm]
      ,[ComputedFieldEnabled]
      ,[DblWindowDisplayedFields]
      ,[DblWindowShowConfidential]
      ,[DblWindowHideToolTip]
      ,[ActiveScroll]
      ,[DisableGroup]
      ,[DetailBkmBarButtons]
      ,[TreeViewUserList]
      ,[FullUserList]
      ,[BkmAutoLinkPmToPPEnabled]
      ,[ObligatReadOnly]
      ,[DisplayFirstBkmOnly]
      ,[IntellimailEnabled]
      ,[InterEventHidden]
      ,[BreakLine]
      ,[SAVEBKMPAGING]
      ,[SelectionSourceTab]
      ,[NoCascadePPPM]
      ,[NoCascadePMPP]
      ,[AutoCompletion]
      ,[IconColor]
      
  FROM [dbo].[DESC] where DescId = @idSubject
END


IF NOT EXISTS (SELECT RESID FROM [RES] WHERE ResId = @idDesc)
BEGIN
INSERT INTO [dbo].[RES]
           ([ResId]
           ,[LANG_00]
           ,[LANG_01]
           ,[LANG_02]
           ,[LANG_03]
           ,[LANG_04]
           ,[LANG_05]
           ,[LANG_06]
           ,[LANG_07]
           ,[LANG_08]
           ,[LANG_09]
           ,[LANG_10])

    SELECT @idDesc,
	[LANG_00]
           ,[LANG_01]
           ,[LANG_02]
           ,[LANG_03]
           ,[LANG_04]
           ,[LANG_05]
           ,[LANG_06]
           ,[LANG_07]
           ,[LANG_08]
           ,[LANG_09]
           ,[LANG_10]
		   From [RES] WHERE resid = @idSubject 

END


