IF NOT EXISTS(SELECT * FROM SYSOBJECTS where id = object_id(N'[dbo].[MAILVERIFSQUERY]') and OBJECTPROPERTY(id, N'IsUserTable') = 1 )
BEGIN
	CREATE TABLE [dbo].[MAILVERIFSQUERY](
	
		[MAILVERIFID] [smallint] IDENTITY(1,1) NOT NULL,
 
		
		[MAILVERIFDATECREA] [datetime] NOT NULL,
		[MAILVERIFDATEMAJ] [datetime]   NULL,
		[MAILVERIFDATESCHEDULE] [datetime]   NULL,		
		[MAILVERIFDATENBTOVERIF] [int]  NULL,
		[MAILVERIFSTATUS] [int] NOT NULL,
		[MAILVERIFUSERID] [numeric](18, 0) NOT NULL,
		[MAILVERIFPARAMS] [nvarchar](max) NULL,
		[MAILVERIFSTATUSINFOS] [nvarchar](max) NULL,
		[MAILVERIFERRORINFOS] [nvarchar](max) NULL,
	 CONSTRAINT [PK_MAILVERIFSQUERY] PRIMARY KEY CLUSTERED 
	(
		[MAILVERIFID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON /*,OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF*/) ON [PRIMARY]
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
	 
END