USE EUDOLOG

IF NOT EXISTS (SELECT * FROM sys.tables tab WHERE tab.name = 'HASH_TO_DB' AND tab.type ='U' )
BEGIN
CREATE TABLE [dbo].[HASH_TO_DB](
	[Id] [int] IDENTITY(1,1) NOT NULL, 
	[HashDatabase] VARCHAR(MAX) NULL, 
	[BaseUID] VARCHAR(20) NULL, 
CONSTRAINT [PK_HASH_TO_DB] PRIMARY KEY CLUSTERED ( [Id] ASC ) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY] ) 
ON [PRIMARY]
END