UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'DZD', [CurrencySymbol] = N'د.ج' WHERE LANG_00 = 'Algérie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EGP', [CurrencySymbol] = N'E£' WHERE LANG_00 = 'Égypte'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'LYD', [CurrencySymbol] = N'ليبي' WHERE LANG_00 = 'Libye'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'MAD', [CurrencySymbol] = N'د.م.' WHERE LANG_00 = 'Maroc'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'MAD', [CurrencySymbol] = N'د.م.' WHERE LANG_00 = 'Sahara occidental'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'MRU', [CurrencySymbol] = N'أوقية' WHERE LANG_00 = 'Mauritanie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'SDG', [CurrencySymbol] = N's£' WHERE LANG_00 = 'Soudan'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'TND', [CurrencySymbol] = N'DT' WHERE LANG_00 = 'Tunisie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'XOF', [CurrencySymbol] = N'F CFA' WHERE LANG_00 = 'Bénin'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'XOF', [CurrencySymbol] = N'F CFA' WHERE LANG_00 = 'Burkina Faso'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'CVE', [CurrencySymbol] = N'escudo' WHERE LANG_00 = 'Cap-Vert'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'XOF', [CurrencySymbol] = N'F CFA' WHERE LANG_00 = 'Côte d’Ivoire'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'GMD', [CurrencySymbol] = N'dalasi' WHERE LANG_00 = 'Gambie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'GHS', [CurrencySymbol] = N'₵' WHERE LANG_00 = 'Ghana'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'GNF', [CurrencySymbol] = N'F' WHERE LANG_00 = 'Guinée'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'XOF', [CurrencySymbol] = N'F CFA' WHERE LANG_00 = 'Guinée-Bissau'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'LRD', [CurrencySymbol] = N'dollar' WHERE LANG_00 = 'Libéria'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'XOF', [CurrencySymbol] = N'F CFA' WHERE LANG_00 = 'Mali'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'XOF', [CurrencySymbol] = N'F CFA' WHERE LANG_00 = 'Niger'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'NGN', [CurrencySymbol] = N'N' WHERE LANG_00 = 'Nigeria'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'XOF', [CurrencySymbol] = N'F CFA' WHERE LANG_00 = 'Sénégal'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'SLL', [CurrencySymbol] = N'leone' WHERE LANG_00 = 'Sierra Leone'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'XOF', [CurrencySymbol] = N'F CFA' WHERE LANG_00 = 'Togo'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'XAF', [CurrencySymbol] = N'F CFA' WHERE LANG_00 = 'Cameroun'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'XAF', [CurrencySymbol] = N'F CFA' WHERE LANG_00 = 'République centrafricaine'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'XAF', [CurrencySymbol] = N'F CFA' WHERE LANG_00 = 'République du Congo'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'CDF', [CurrencySymbol] = N'F/FC' WHERE LANG_00 = 'République démocratique du Congo'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'XAF', [CurrencySymbol] = N'F CFA' WHERE LANG_00 = 'Gabon'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'XAF', [CurrencySymbol] = N'F CFA' WHERE LANG_00 = 'Guinée équatoriale'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'STD', [CurrencySymbol] = N'dobra' WHERE LANG_00 = 'Sao Tomé-et-Principe'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'XAF', [CurrencySymbol] = N'F CFA' WHERE LANG_00 = 'Tchad'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'BIF', [CurrencySymbol] = N'F' WHERE LANG_00 = 'Burundi'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'DJF', [CurrencySymbol] = N'F' WHERE LANG_00 = 'Djibouti'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'ERN', [CurrencySymbol] = N'nafka' WHERE LANG_00 = 'Érythrée'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'ETB', [CurrencySymbol] = N'birr' WHERE LANG_00 = 'Éthiopie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'KES', [CurrencySymbol] = N'shilling' WHERE LANG_00 = 'Kenya'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'UGX', [CurrencySymbol] = N'shilling' WHERE LANG_00 = 'Ouganda'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'RWF', [CurrencySymbol] = N'F' WHERE LANG_00 = 'Rwanda'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'SCR', [CurrencySymbol] = N'roupie' WHERE LANG_00 = 'Seychelles'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'SOS', [CurrencySymbol] = N'shilling' WHERE LANG_00 = 'Somalie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'SSP', [CurrencySymbol] = N'SS£' WHERE LANG_00 = 'Sud-Soudan'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'TZS', [CurrencySymbol] = N'shilling' WHERE LANG_00 = 'Tanzanie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'ZAR', [CurrencySymbol] = N'R' WHERE LANG_00 = 'Afrique du Sud'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'AOA', [CurrencySymbol] = N'Kz' WHERE LANG_00 = 'Angola'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'BWP', [CurrencySymbol] = N'pula' WHERE LANG_00 = 'Botswana'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'NOK', [CurrencySymbol] = N'krone' WHERE LANG_00 = 'Île Bouvet'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'KMF', [CurrencySymbol] = N'FC' WHERE LANG_00 = 'Comores'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Réunion'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'LSL', [CurrencySymbol] = N'loti' WHERE LANG_00 = 'Lesotho'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'MGA', [CurrencySymbol] = N'ariary' WHERE LANG_00 = 'Madagascar'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'MWK', [CurrencySymbol] = N'kwacha' WHERE LANG_00 = 'Malawi'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'MUR', [CurrencySymbol] = N'roupie' WHERE LANG_00 = 'Maurice'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Mayotte'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'MZN', [CurrencySymbol] = N'MTn' WHERE LANG_00 = 'Mozambique'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'NAD', [CurrencySymbol] = N'dollar' WHERE LANG_00 = 'Namibie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'SHP', [CurrencySymbol] = N'£' WHERE LANG_00 = 'Sainte-Hélène'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'SZL', [CurrencySymbol] = N'lilangeni' WHERE LANG_00 = 'Eswatini'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Terres australes et antarctiques françaises'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'ZMW', [CurrencySymbol] = N'kwacha' WHERE LANG_00 = 'Zambie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'ZWL', [CurrencySymbol] = N'dollar' WHERE LANG_00 = 'Zimbabwe'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'KZT', [CurrencySymbol] = N'tеңге' WHERE LANG_00 = 'Kazakhstan'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'KGS', [CurrencySymbol] = N'som' WHERE LANG_00 = 'Kirghizistan'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'UZS', [CurrencySymbol] = N'sum' WHERE LANG_00 = 'Ouzbékistan'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'TJS', [CurrencySymbol] = N'somoni' WHERE LANG_00 = 'Tadjikistan'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'TMT', [CurrencySymbol] = N'manat' WHERE LANG_00 = 'Turkménistan'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'AMD', [CurrencySymbol] = N'դրամ' WHERE LANG_00 = 'Arménie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'AZN', [CurrencySymbol] = N'₼' WHERE LANG_00 = 'Azerbaïdjan'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'GEL', [CurrencySymbol] = N'₾' WHERE LANG_00 = 'Géorgie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'RUB', [CurrencySymbol] = N'₽' WHERE LANG_00 = 'Russie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'CNY', [CurrencySymbol] = N'¥' WHERE LANG_00 = 'Chine'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'KPW', [CurrencySymbol] = N'￦' WHERE LANG_00 = 'Corée du Nord'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'KRW', [CurrencySymbol] = N'￦' WHERE LANG_00 = 'Corée du Sud'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'HKD', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Hong Kong'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'JPY', [CurrencySymbol] = N'¥' WHERE LANG_00 = 'Japon'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'MOP', [CurrencySymbol] = N'?' WHERE LANG_00 = 'Macao'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'MNT', [CurrencySymbol] = N'₮' WHERE LANG_00 = 'Mongolie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'TWD', [CurrencySymbol] = N'元' WHERE LANG_00 = 'Taïwan'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'AFN', [CurrencySymbol] = N'؋' WHERE LANG_00 = 'Afghanistan'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'SAR', [CurrencySymbol] = N'riyal' WHERE LANG_00 = 'Arabie saoudite'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'BHD', [CurrencySymbol] = N'dinar' WHERE LANG_00 = 'Bahreïn'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'AED', [CurrencySymbol] = N'DH' WHERE LANG_00 = 'Émirats arabes unis'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'IRR', [CurrencySymbol] = N'ریال ایران' WHERE LANG_00 = 'Iran'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'IQD', [CurrencySymbol] = N'dinar' WHERE LANG_00 = 'Irak'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'ILS', [CurrencySymbol] = N'₪' WHERE LANG_00 = 'Israël'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'JOD', [CurrencySymbol] = N'dinar' WHERE LANG_00 = 'Jordanie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'KWD', [CurrencySymbol] = N'dinar' WHERE LANG_00 = 'Koweït'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'LBP', [CurrencySymbol] = N'£L' WHERE LANG_00 = 'Liban'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'OMR', [CurrencySymbol] = N'rial' WHERE LANG_00 = 'Oman'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'ILS', [CurrencySymbol] = N'₪' WHERE LANG_00 = 'Palestine'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'QAR', [CurrencySymbol] = N'rial' WHERE LANG_00 = 'Qatar'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'SYP', [CurrencySymbol] = N'S£' WHERE LANG_00 = 'Syrie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'TRY', [CurrencySymbol] = N'₺' WHERE LANG_00 = 'Turquie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'YER', [CurrencySymbol] = N'rial' WHERE LANG_00 = 'Yémen'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'MMK', [CurrencySymbol] = N'kyat' WHERE LANG_00 = 'Myanmar'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'BND', [CurrencySymbol] = N'B$' WHERE LANG_00 = 'Brunei Darussalam'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'KHR', [CurrencySymbol] = N'riel' WHERE LANG_00 = 'Cambodge'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'IDR', [CurrencySymbol] = N'roupie' WHERE LANG_00 = 'Indonésie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'LAK', [CurrencySymbol] = N'₭' WHERE LANG_00 = 'Laos'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'MYR', [CurrencySymbol] = N'RM' WHERE LANG_00 = 'Malaisie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'PHP', [CurrencySymbol] = N'peso' WHERE LANG_00 = 'Philippines'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'SGD', [CurrencySymbol] = N'S$' WHERE LANG_00 = 'Singapour'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'THB', [CurrencySymbol] = N'฿' WHERE LANG_00 = 'Thaïlande'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'USD', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Timor-Leste'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'VND', [CurrencySymbol] = N'đồng' WHERE LANG_00 = 'Viêt Nam'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'BDT', [CurrencySymbol] = N'taka' WHERE LANG_00 = 'Bangladesh'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'BTN', [CurrencySymbol] = N'Nu' WHERE LANG_00 = 'Bhoutan'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'INR', [CurrencySymbol] = N'Rs.' WHERE LANG_00 = 'Inde'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'INR', [CurrencySymbol] = N'₹' WHERE LANG_00 = 'Inde'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'MVR', [CurrencySymbol] = N'rf' WHERE LANG_00 = 'Maldives'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'NPR', [CurrencySymbol] = N'रूपैयाँ' WHERE LANG_00 = 'Népal'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'PKR', [CurrencySymbol] = N'₨' WHERE LANG_00 = 'Pakistan'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'LKR', [CurrencySymbol] = N'₨' WHERE LANG_00 = 'Sri Lanka'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'BMD', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Bermudes'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'CAD', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Canada'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'USD', [CurrencySymbol] = N'$' WHERE LANG_00 = 'États-Unis'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'USD', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Antarctique'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'DKK', [CurrencySymbol] = N'kr' WHERE LANG_00 = 'Groenland'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'MXN', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Mexique'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Saint-Pierre-et-Miquelon'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'BZD', [CurrencySymbol] = N'BZ$' WHERE LANG_00 = 'Belize'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'CRC', [CurrencySymbol] = N'colón' WHERE LANG_00 = 'Costa Rica'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'GTQ', [CurrencySymbol] = N'quetzal' WHERE LANG_00 = 'Guatemala'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'HNL', [CurrencySymbol] = N'lempira' WHERE LANG_00 = 'Honduras'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'NIO', [CurrencySymbol] = N'córdoba' WHERE LANG_00 = 'Nicaragua'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'PAB', [CurrencySymbol] = N'balboa' WHERE LANG_00 = 'Panama'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'USD', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Salvador'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'XCD', [CurrencySymbol] = N'EC$' WHERE LANG_00 = 'Anguilla'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'XCD', [CurrencySymbol] = N'EC$' WHERE LANG_00 = 'Antigua-et-Barbuda'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'AWG', [CurrencySymbol] = N'Aƒ' WHERE LANG_00 = 'Aruba'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'BSD', [CurrencySymbol] = N'B$' WHERE LANG_00 = 'Bahamas'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'BBD', [CurrencySymbol] = N'Bds$' WHERE LANG_00 = 'Barbade'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'KYD', [CurrencySymbol] = N'CI$' WHERE LANG_00 = 'Îles Caïmans'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'CUP', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Cuba'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'CUC', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Cuba'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'ANG', [CurrencySymbol] = N'Naƒ' WHERE LANG_00 = 'Curaçao'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'DOP', [CurrencySymbol] = N'$' WHERE LANG_00 = 'République dominicaine'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'XCD', [CurrencySymbol] = N'EC$' WHERE LANG_00 = 'Dominique'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'XCD', [CurrencySymbol] = N'EC$' WHERE LANG_00 = 'Grenade'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Guadeloupe'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'HTG', [CurrencySymbol] = N'gourde' WHERE LANG_00 = 'Haïti'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'JMD', [CurrencySymbol] = N'J$' WHERE LANG_00 = 'Jamaïque'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Martinique'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'XCD', [CurrencySymbol] = N'EC$' WHERE LANG_00 = 'Montserrat'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'USD', [CurrencySymbol] = N'dollar' WHERE LANG_00 = 'Pays-Bas caribéens'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'USD', [CurrencySymbol] = N'dollar' WHERE LANG_00 = 'Puerto Rico'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Saint-Barthélemy'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'XCD', [CurrencySymbol] = N'EC$' WHERE LANG_00 = 'Saint-Christophe-et-Niévès'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Saint-Martin (partie française)'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'XCD', [CurrencySymbol] = N'EC$' WHERE LANG_00 = 'Saint-Vincent-et-les-Grenadines'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'XCD', [CurrencySymbol] = N'EC$' WHERE LANG_00 = 'Sainte-Lucie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'ANG', [CurrencySymbol] = N'Naƒ' WHERE LANG_00 = 'Saint-Martin (partie néerlandaise)'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'TTD', [CurrencySymbol] = N'TTD' WHERE LANG_00 = 'Trinité-et-Tobago'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'USD', [CurrencySymbol] = N'dollar' WHERE LANG_00 = 'Îles Turques-et-Caïques'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'USD', [CurrencySymbol] = N'dollar' WHERE LANG_00 = 'Îles Vierges britanniques'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'USD', [CurrencySymbol] = N'dollar' WHERE LANG_00 = 'Îles Vierges américaines'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'ARS', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Argentine'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'BOB', [CurrencySymbol] = N'boliviano' WHERE LANG_00 = 'Bolivie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'BRL', [CurrencySymbol] = N'R$' WHERE LANG_00 = 'Brésil'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'CLP', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Chili'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'COP', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Colombie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'USD', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Équateur'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'FKP', [CurrencySymbol] = N'£' WHERE LANG_00 = 'Géorgie du Sud et les îles Sandwich du Sud'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'GYD', [CurrencySymbol] = N'G$' WHERE LANG_00 = 'Guyane'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Guyane française'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'FKP', [CurrencySymbol] = N'£' WHERE LANG_00 = 'Îles Falkland'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'PYG', [CurrencySymbol] = N'₲' WHERE LANG_00 = 'Paraguay'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'PEN', [CurrencySymbol] = N'S/.' WHERE LANG_00 = 'Pérou'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'SRD', [CurrencySymbol] = N'dollar' WHERE LANG_00 = 'Suriname'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'UYU', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Uruguay'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'VES', [CurrencySymbol] = N'bolívar' WHERE LANG_00 = 'Venezuela'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Allemagne'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Autriche'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Belgique'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Chypre'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Espagne'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Estonie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Finlande'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Îles Åland'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'France'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Grèce'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Irlande'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Italie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Lettonie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Lituanie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Luxembourg'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Malte'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Pays-Bas'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Portugal'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Slovaquie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Slovénie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'BGN', [CurrencySymbol] = N'лев' WHERE LANG_00 = 'Bulgarie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'HRK', [CurrencySymbol] = N'kuna' WHERE LANG_00 = 'Croatie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'DKK', [CurrencySymbol] = N'kr' WHERE LANG_00 = 'Danemark'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'HUF', [CurrencySymbol] = N'Ft' WHERE LANG_00 = 'Hongrie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'PLN', [CurrencySymbol] = N'złoty' WHERE LANG_00 = 'Pologne'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'SEK', [CurrencySymbol] = N'krona' WHERE LANG_00 = 'Suède'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'CZK', [CurrencySymbol] = N'koruna' WHERE LANG_00 = 'République tchèque'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'RON', [CurrencySymbol] = N'leu' WHERE LANG_00 = 'Roumanie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Andorre'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'ALL', [CurrencySymbol] = N'lek' WHERE LANG_00 = 'Albanie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'BYN', [CurrencySymbol] = N'Br.' WHERE LANG_00 = 'Biélorussie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'BAM', [CurrencySymbol] = N'MK' WHERE LANG_00 = 'Bosnie-Herzégovine'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'DKK', [CurrencySymbol] = N'kr' WHERE LANG_00 = 'Îles Féroé'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'GBP', [CurrencySymbol] = N'£' WHERE LANG_00 = 'Guernesey'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'ISK', [CurrencySymbol] = N'króna' WHERE LANG_00 = 'Islande'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'GBP', [CurrencySymbol] = N'£' WHERE LANG_00 = 'Jersey'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Kosovo'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'CHF', [CurrencySymbol] = N'CHF' WHERE LANG_00 = 'Liechtenstein'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'MKD', [CurrencySymbol] = N'ден' WHERE LANG_00 = 'Macédoine'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'GBP', [CurrencySymbol] = N'£' WHERE LANG_00 = 'Île de Man'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'MDL', [CurrencySymbol] = N'leu' WHERE LANG_00 = 'Moldavie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Monaco'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Monténégro'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'NOK', [CurrencySymbol] = N'krone' WHERE LANG_00 = 'Norvège'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'NOK', [CurrencySymbol] = N'krone' WHERE LANG_00 = 'Svalbard et Jan Mayen'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'GBP', [CurrencySymbol] = N'£' WHERE LANG_00 = 'Royaume-Uni'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'GBP', [CurrencySymbol] = N'£' WHERE LANG_00 = 'Territoire britannique de l’Océan Indien'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'GIP', [CurrencySymbol] = N'Gibraltar pound' WHERE LANG_00 = 'Gibraltar'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Saint-Marin'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'RSD', [CurrencySymbol] = N'РСД' WHERE LANG_00 = 'Serbie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'CHF', [CurrencySymbol] = N'CHF' WHERE LANG_00 = 'Suisse'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'UAH', [CurrencySymbol] = N'₴' WHERE LANG_00 = 'Ukraine'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'EUR', [CurrencySymbol] = N'€' WHERE LANG_00 = 'Saint-Siège (Vatican)'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'AUD', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Australie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'AUD', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Île Christmas'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'AUD', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Îles Cocos'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'NZD', [CurrencySymbol] = N'dollar' WHERE LANG_00 = 'Îles Cook'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'FJD', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Fidji'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'USD', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Guam'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'AUD', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Îles Heard-et-MacDonald'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'AUD', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Kiribati'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'USD', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Îles Mariannes du Nord'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'USD', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Îles Marshall'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'USD', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Micronésie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'USD', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Îles mineures éloignées des États-Unis'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'AUD', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Nauru'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'NZD', [CurrencySymbol] = N'dollar' WHERE LANG_00 = 'Tokelau'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'NZD', [CurrencySymbol] = N'dollar' WHERE LANG_00 = 'Niue'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'AUD', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Île Norfolk'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'XPF', [CurrencySymbol] = N'F CFP' WHERE LANG_00 = 'Nouvelle-Calédonie'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'NZD', [CurrencySymbol] = N'dollar' WHERE LANG_00 = 'Nouvelle-Zélande'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'USD', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Palaos'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'PGK', [CurrencySymbol] = N'kina' WHERE LANG_00 = 'Papouasie-Nouvelle-Guinée'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'NZD', [CurrencySymbol] = N'dollar' WHERE LANG_00 = 'Îles Pitcairn'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'XPF', [CurrencySymbol] = N'F CFP' WHERE LANG_00 = 'Polynésie française'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'SBD', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Îles Salomon'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'WST', [CurrencySymbol] = N'tala' WHERE LANG_00 = 'Samoa'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'USD', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Samoa américaines'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'TOP', [CurrencySymbol] = N'paʻanga' WHERE LANG_00 = 'Tonga'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'AUD', [CurrencySymbol] = N'$' WHERE LANG_00 = 'Tuvalu'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'VUV', [CurrencySymbol] = N'vatu' WHERE LANG_00 = 'Vanuatu'
UPDATE [EDNCOUNTRIES] SET [CurrencyCode] = 'XPF', [CurrencySymbol] = N'F CFP' WHERE LANG_00 = 'Wallis-et-Futuna'