IF NOT EXISTS (
		SELECT 1
		FROM sys.tables
		WHERE name LIKE 'EDNCOUNTRIES'
		)
BEGIN
	CREATE TABLE dbo.[EDNCOUNTRIES] (
		[Id] INT NOT NULL
		,[ALPHA2] CHAR(2) NOT NULL
		,[ALPHA3] CHAR(3) NOT NULL
		,[LANG_00] VARCHAR(56) NOT NULL
		)
END
