INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 4, 'AF', 'AFG', 'Afghanistan'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Afghanistan')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 248, 'AX', 'ALA', 'Îles Åland'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Îles Åland')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 8, 'AL', 'ALB', 'Albanie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Albanie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 12, 'DZ', 'DZA', 'Algérie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Algérie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 16, 'AS', 'ASM', 'Samoa américaines'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Samoa américaines')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 20, 'AD', 'AND', 'Andorre'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Andorre')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 24, 'AO', 'AGO', 'Angola'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Angola')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 660, 'AI', 'AIA', 'Anguilla'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Anguilla')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 10, 'AQ', 'ATA', 'Antarctique'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Antarctique')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 28, 'AG', 'ATG', 'Antigua-et-Barbuda'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Antigua-et-Barbuda')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 32, 'AR', 'ARG', 'Argentine'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Argentine')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 51, 'AM', 'ARM', 'Arménie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Arménie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 533, 'AW', 'ABW', 'Aruba'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Aruba')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 36, 'AU', 'AUS', 'Australie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Australie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 40, 'AT', 'AUT', 'Autriche'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Autriche')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 31, 'AZ', 'AZE', 'Azerbaïdjan'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Azerbaïdjan')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 44, 'BS', 'BHS', 'Bahamas'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Bahamas')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 48, 'BH', 'BHR', 'Bahreïn'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Bahreïn')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 50, 'BD', 'BGD', 'Bangladesh'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Bangladesh')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 52, 'BB', 'BRB', 'Barbade'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Barbade')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 112, 'BY', 'BLR', 'Biélorussie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Biélorussie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 56, 'BE', 'BEL', 'Belgique'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Belgique')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 84, 'BZ', 'BLZ', 'Belize'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Belize')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 204, 'BJ', 'BEN', 'Bénin'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Bénin')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 60, 'BM', 'BMU', 'Bermudes'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Bermudes')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 64, 'BT', 'BTN', 'Bhoutan'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Bhoutan')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 68, 'BO', 'BOL', 'Bolivie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Bolivie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 70, 'BA', 'BIH', 'Bosnie-Herzégovine'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Bosnie-Herzégovine')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 72, 'BW', 'BWA', 'Botswana'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Botswana')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 74, 'BV', 'BVT', 'Île Bouvet'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Île Bouvet')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 76, 'BR', 'BRA', 'Brésil'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Brésil')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 92, 'VG', 'VGB', 'British Virgin Islands'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'British Virgin Islands')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 86, 'IO', 'IOT', 'Territoire britannique de l’Océan Indien'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Territoire britannique de l’Océan Indien')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 96, 'BN', 'BRN', 'Brunei Darussalam'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Brunei Darussalam')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 100, 'BG', 'BGR', 'Bulgarie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Bulgarie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 854, 'BF', 'BFA', 'Burkina Faso'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Burkina Faso')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 108, 'BI', 'BDI', 'Burundi'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Burundi')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 116, 'KH', 'KHM', 'Cambodge'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Cambodge')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 120, 'CM', 'CMR', 'Cameroun'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Cameroun')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 124, 'CA', 'CAN', 'Canada'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Canada')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 132, 'CV', 'CPV', 'Cap-Vert'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Cap-Vert')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 136, 'KY', 'CYM', 'Iles Cayman'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Iles Cayman')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 140, 'CF', 'CAF', 'République centrafricaine'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'République centrafricaine')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 148, 'TD', 'TCD', 'Tchad'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Tchad')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 152, 'CL', 'CHL', 'Chili'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Chili')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 156, 'CN', 'CHN', 'Chine'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Chine')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 344, 'HK', 'HKG', 'Hong Kong'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Hong Kong')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 446, 'MO', 'MAC', 'Macao'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Macao')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 162, 'CX', 'CXR', 'Île Christmas'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Île Christmas')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 166, 'CC', 'CCK', 'Îles Cocos'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Îles Cocos')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 170, 'CO', 'COL', 'Colombie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Colombie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 174, 'KM', 'COM', 'Comores'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Comores')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 178, 'CG', 'COG', 'République du Congo'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'République du Congo')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 180, 'CD', 'COD', 'République démocratique du Congo'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'République démocratique du Congo')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 184, 'CK', 'COK', 'Îles Cook'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Îles Cook')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 188, 'CR', 'CRI', 'Costa Rica'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Costa Rica')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 384, 'CI', 'CIV', 'Côte d’Ivoire'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Côte d’Ivoire')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 191, 'HR', 'HRV', 'Croatie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Croatie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 192, 'CU', 'CUB', 'Cuba'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Cuba')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 196, 'CY', 'CYP', 'Chypre'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Chypre')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 203, 'CZ', 'CZE', 'République tchèque'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'République tchèque')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 208, 'DK', 'DNK', 'Danemark'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Danemark')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 262, 'DJ', 'DJI', 'Djibouti'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Djibouti')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 212, 'DM', 'DMA', 'Dominique'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Dominique')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 214, 'DO', 'DOM', 'République dominicaine'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'République dominicaine')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 218, 'EC', 'ECU', 'Équateur'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Équateur')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 818, 'EG', 'EGY', 'Égypte'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Égypte')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 222, 'SV', 'SLV', 'Salvador'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Salvador')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 226, 'GQ', 'GNQ', 'Guinée équatoriale'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Guinée équatoriale')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 232, 'ER', 'ERI', 'Érythrée'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Érythrée')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 233, 'EE', 'EST', 'Estonie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Estonie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 231, 'ET', 'ETH', 'Éthiopie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Éthiopie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 238, 'FK', 'FLK', 'Îles Falkland'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Îles Falkland')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 234, 'FO', 'FRO', 'Îles Féroé'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Îles Féroé')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 242, 'FJ', 'FJI', 'Fidji'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Fidji')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 246, 'FI', 'FIN', 'Finlande'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Finlande')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 250, 'FR', 'FRA', 'France'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'France')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 254, 'GF', 'GUF', 'Guyane française'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Guyane française')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 258, 'PF', 'PYF', 'Polynésie française'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Polynésie française')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 260, 'TF', 'ATF', 'Terres australes et antarctiques françaises'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Terres australes et antarctiques françaises')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 266, 'GA', 'GAB', 'Gabon'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Gabon')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 270, 'GM', 'GMB', 'Gambie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Gambie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 268, 'GE', 'GEO', 'Géorgie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Géorgie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 276, 'DE', 'DEU', 'Allemagne'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Allemagne')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 288, 'GH', 'GHA', 'Ghana'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Ghana')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 292, 'GI', 'GIB', 'Gibraltar'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Gibraltar')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 300, 'GR', 'GRC', 'Grèce'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Grèce')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 304, 'GL', 'GRL', 'Groenland'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Groenland')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 308, 'GD', 'GRD', 'Grenade'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Grenade')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 312, 'GP', 'GLP', 'Guadeloupe'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Guadeloupe')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 316, 'GU', 'GUM', 'Guam'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Guam')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 320, 'GT', 'GTM', 'Guatemala'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Guatemala')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 831, 'GG', 'GGY', 'Guernesey'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Guernesey')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 324, 'GN', 'GIN', 'Guinée'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Guinée')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 624, 'GW', 'GNB', 'Guinée-Bissau'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Guinée-Bissau')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 328, 'GY', 'GUY', 'Guyane'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Guyane')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 332, 'HT', 'HTI', 'Haïti'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Haïti')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 334, 'HM', 'HMD', 'Îles Heard-et-MacDonald'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Îles Heard-et-MacDonald')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 336, 'VA', 'VAT', 'Saint-Siège (Vatican)'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Saint-Siège (Vatican)')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 340, 'HN', 'HND', 'Honduras'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Honduras')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 348, 'HU', 'HUN', 'Hongrie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Hongrie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 352, 'IS', 'ISL', 'Islande'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Islande')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 356, 'IN', 'IND', 'Inde'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Inde')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 360, 'ID', 'IDN', 'Indonésie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Indonésie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 364, 'IR', 'IRN', 'Iran'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Iran')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 368, 'IQ', 'IRQ', 'Irak'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Irak')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 372, 'IE', 'IRL', 'Irlande'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Irlande')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 833, 'IM', 'IMN', 'Ile de Man'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Ile de Man')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 376, 'IL', 'ISR', 'Israël'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Israël')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 380, 'IT', 'ITA', 'Italie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Italie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 388, 'JM', 'JAM', 'Jamaïque'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Jamaïque')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 392, 'JP', 'JPN', 'Japon'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Japon')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 832, 'JE', 'JEY', 'Jersey'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Jersey')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 400, 'JO', 'JOR', 'Jordanie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Jordanie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 398, 'KZ', 'KAZ', 'Kazakhstan'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Kazakhstan')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 404, 'KE', 'KEN', 'Kenya'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Kenya')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 296, 'KI', 'KIR', 'Kiribati'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Kiribati')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 408, 'KP', 'PRK', 'Corée du Nord'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Corée du Nord')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 410, 'KR', 'KOR', 'Corée du Sud'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Corée du Sud')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 414, 'KW', 'KWT', 'Koweït'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Koweït')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 417, 'KG', 'KGZ', 'Kirghizistan'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Kirghizistan')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 418, 'LA', 'LAO', 'Laos'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Laos')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 428, 'LV', 'LVA', 'Lettonie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Lettonie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 422, 'LB', 'LBN', 'Liban'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Liban')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 426, 'LS', 'LSO', 'Lesotho'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Lesotho')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 430, 'LR', 'LBR', 'Libéria'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Libéria')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 434, 'LY', 'LBY', 'Libye'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Libye')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 438, 'LI', 'LIE', 'Liechtenstein'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Liechtenstein')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 440, 'LT', 'LTU', 'Lituanie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Lituanie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 442, 'LU', 'LUX', 'Luxembourg'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Luxembourg')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 807, 'MK', 'MKD', 'Macédoine'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Macédoine')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 450, 'MG', 'MDG', 'Madagascar'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Madagascar')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 454, 'MW', 'MWI', 'Malawi'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Malawi')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 458, 'MY', 'MYS', 'Malaisie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Malaisie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 462, 'MV', 'MDV', 'Maldives'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Maldives')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 466, 'ML', 'MLI', 'Mali'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Mali')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 470, 'MT', 'MLT', 'Malte'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Malte')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 584, 'MH', 'MHL', 'Îles Marshall'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Îles Marshall')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 474, 'MQ', 'MTQ', 'Martinique'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Martinique')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 478, 'MR', 'MRT', 'Mauritanie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Mauritanie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 480, 'MU', 'MUS', 'Maurice'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Maurice')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 175, 'YT', 'MYT', 'Mayotte'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Mayotte')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 484, 'MX', 'MEX', 'Mexique'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Mexique')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 583, 'FM', 'FSM', 'Micronésie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Micronésie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 498, 'MD', 'MDA', 'Moldavie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Moldavie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 492, 'MC', 'MCO', 'Monaco'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Monaco')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 496, 'MN', 'MNG', 'Mongolie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Mongolie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 499, 'ME', 'MNE', 'Monténégro'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Monténégro')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 500, 'MS', 'MSR', 'Montserrat'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Montserrat')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 504, 'MA', 'MAR', 'Maroc'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Maroc')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 508, 'MZ', 'MOZ', 'Mozambique'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Mozambique')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 104, 'MM', 'MMR', 'Myanmar'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Myanmar')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 516, 'NA', 'NAM', 'Namibie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Namibie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 520, 'NR', 'NRU', 'Nauru'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Nauru')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 524, 'NP', 'NPL', 'Népal'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Népal')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 528, 'NL', 'NLD', 'Pays-Bas'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Pays-Bas')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 540, 'NC', 'NCL', 'Nouvelle-Calédonie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Nouvelle-Calédonie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 554, 'NZ', 'NZL', 'Nouvelle-Zélande'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Nouvelle-Zélande')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 558, 'NI', 'NIC', 'Nicaragua'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Nicaragua')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 562, 'NE', 'NER', 'Niger'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Niger')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 566, 'NG', 'NGA', 'Nigeria'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Nigeria')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 570, 'NU', 'NIU', 'Niue'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Niue')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 574, 'NF', 'NFK', 'Île Norfolk'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Île Norfolk')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 580, 'MP', 'MNP', 'Îles Mariannes du Nord'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Îles Mariannes du Nord')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 578, 'NO', 'NOR', 'Norvège'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Norvège')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 512, 'OM', 'OMN', 'Oman'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Oman')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 586, 'PK', 'PAK', 'Pakistan'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Pakistan')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 585, 'PW', 'PLW', 'Palau'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Palau')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 275, 'PS', 'PSE', 'Palestine'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Palestine')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 591, 'PA', 'PAN', 'Panama'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Panama')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 598, 'PG', 'PNG', 'Papouasie-Nouvelle-Guinée'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Papouasie-Nouvelle-Guinée')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 600, 'PY', 'PRY', 'Paraguay'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Paraguay')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 604, 'PE', 'PER', 'Pérou'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Pérou')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 608, 'PH', 'PHL', 'Philippines'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Philippines')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 612, 'PN', 'PCN', 'Pitcairn'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Pitcairn')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 616, 'PL', 'POL', 'Pologne'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Pologne')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 620, 'PT', 'PRT', 'Portugal'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Portugal')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 630, 'PR', 'PRI', 'Puerto Rico'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Puerto Rico')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 634, 'QA', 'QAT', 'Qatar'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Qatar')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 638, 'RE', 'REU', 'Réunion'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Réunion')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 642, 'RO', 'ROU', 'Roumanie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Roumanie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 643, 'RU', 'RUS', 'Russie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Russie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 646, 'RW', 'RWA', 'Rwanda'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Rwanda')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 652, 'BL', 'BLM', 'Saint-Barthélemy'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Saint-Barthélemy')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 654, 'SH', 'SHN', 'Sainte-Hélène'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Sainte-Hélène')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 659, 'KN', 'KNA', 'Saint-Kitts-et-Nevis'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Saint-Kitts-et-Nevis')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 662, 'LC', 'LCA', 'Sainte-Lucie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Sainte-Lucie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 663, 'MF', 'MAF', 'Saint-Martin (partie française)'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Saint-Martin (partie française)')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 534, 'SX', 'SXM', 'Saint-Martin (partie néerlandaise)'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Saint-Martin (partie néerlandaise)')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 666, 'PM', 'SPM', 'Saint-Pierre-et-Miquelon'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Saint-Pierre-et-Miquelon')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 670, 'VC', 'VCT', 'Saint-Vincent-et-les Grenadines'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Saint-Vincent-et-les Grenadines')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 882, 'WS', 'WSM', 'Samoa'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Samoa')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 674, 'SM', 'SMR', 'Saint-Marin'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Saint-Marin')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 678, 'ST', 'STP', 'Sao Tomé-et-Principe'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Sao Tomé-et-Principe')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 682, 'SA', 'SAU', 'Arabie Saoudite'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Arabie Saoudite')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 686, 'SN', 'SEN', 'Sénégal'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Sénégal')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 688, 'RS', 'SRB', 'Serbie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Serbie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 690, 'SC', 'SYC', 'Seychelles'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Seychelles')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 694, 'SL', 'SLE', 'Sierra Leone'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Sierra Leone')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 702, 'SG', 'SGP', 'Singapour'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Singapour')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 703, 'SK', 'SVK', 'Slovaquie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Slovaquie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 705, 'SI', 'SVN', 'Slovénie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Slovénie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 90, 'SB', 'SLB', 'Îles Salomon'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Îles Salomon')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 706, 'SO', 'SOM', 'Somalie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Somalie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 710, 'ZA', 'ZAF', 'Afrique du Sud'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Afrique du Sud')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 239, 'GS', 'SGS', 'Géorgie du Sud et les îles Sandwich du Sud'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Géorgie du Sud et les îles Sandwich du Sud')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 728, 'SS', 'SSD', 'Sud-Soudan'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Sud-Soudan')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 724, 'ES', 'ESP', 'Espagne'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Espagne')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 144, 'LK', 'LKA', 'Sri Lanka'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Sri Lanka')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 736, 'SD', 'SDN', 'Soudan'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Soudan')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 740, 'SR', 'SUR', 'Suriname'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Suriname')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 744, 'SJ', 'SJM', 'Svalbard et Jan Mayen'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Svalbard et Jan Mayen')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 748, 'SZ', 'SWZ', 'Eswatini'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Eswatini')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 752, 'SE', 'SWE', 'Suède'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Suède')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 756, 'CH', 'CHE', 'Suisse'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Suisse')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 760, 'SY', 'SYR', 'Syrie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Syrie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 158, 'TW', 'TWN', 'Taiwan'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Taiwan')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 762, 'TJ', 'TJK', 'Tadjikistan'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Tadjikistan')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 834, 'TZ', 'TZA', 'Tanzanie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Tanzanie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 764, 'TH', 'THA', 'Thaïlande'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Thaïlande')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 626, 'TL', 'TLS', 'Timor-Leste'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Timor-Leste')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 768, 'TG', 'TGO', 'Togo'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Togo')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 772, 'TK', 'TKL', 'Tokelau'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Tokelau')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 776, 'TO', 'TON', 'Tonga'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Tonga')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 780, 'TT', 'TTO', 'Trinité-et-Tobago'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Trinité-et-Tobago')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 788, 'TN', 'TUN', 'Tunisie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Tunisie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 792, 'TR', 'TUR', 'Turquie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Turquie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 795, 'TM', 'TKM', 'Turkménistan'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Turkménistan')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 796, 'TC', 'TCA', 'Îles Turques-et-Caïques'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Îles Turques-et-Caïques')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 798, 'TV', 'TUV', 'Tuvalu'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Tuvalu')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 800, 'UG', 'UGA', 'Ouganda'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Ouganda')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 804, 'UA', 'UKR', 'Ukraine'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Ukraine')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 784, 'AE', 'ARE', 'Émirats Arabes Unis'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Émirats Arabes Unis')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 826, 'GB', 'GBR', 'Royaume-Uni'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Royaume-Uni')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 840, 'US', 'USA', 'États-Unis'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'États-Unis')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 581, 'UM', 'UMI', 'Îles mineures éloignées des États-Unis'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Îles mineures éloignées des États-Unis')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 858, 'UY', 'URY', 'Uruguay'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Uruguay')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 860, 'UZ', 'UZB', 'Ouzbékistan'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Ouzbékistan')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 548, 'VU', 'VUT', 'Vanuatu'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Vanuatu')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 862, 'VE', 'VEN', 'Venezuela'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Venezuela')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 704, 'VN', 'VNM', 'Viêt Nam'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Viêt Nam')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 850, 'VI', 'VIR', 'Îles Vierges américaines'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Îles Vierges américaines')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 876, 'WF', 'WLF', 'Wallis-et-Futuna'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Wallis-et-Futuna')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 732, 'EH', 'ESH', 'Sahara occidental'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Sahara occidental')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 887, 'YE', 'YEM', 'Yémen'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Yémen')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 894, 'ZM', 'ZMB', 'Zambie'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Zambie')

INSERT INTO EDNCOUNTRIES(Id, Alpha2, Alpha3, Lang_00) SELECT 716, 'ZW', 'ZWE', 'Zimbabwe'
WHERE NOT EXISTS (SELECT Id From EDNCOUNTRIES WHERE LANG_00 = 'Zimbabwe')
