IF EXISTS (SELECT * FROM [CONFIGADV] WHERE [Parameter] = 'CREATE_PP_WITHOUT_ADR')
AND NOT EXISTS (SELECT * FROM [CONFIGADV] WHERE [Parameter] = 'CREATE_PP_ADR_MODE')
BEGIN
	INSERT INTO [CONFIGADV] ([Parameter], [Value])
	SELECT 'CREATE_PP_ADR_MODE', CASE WHEN (SELECT TOP 1 [Value] FROM [CONFIGADV] WHERE [Parameter] = 'CREATE_PP_WITHOUT_ADR') = '1' THEN '1' ELSE '0' END
END
