 
 

 if EXISTS (SELECT * 
FROM sys.indexes 
WHERE name='IX_BOUND' AND object_id = OBJECT_ID('[DESC]'))
DROP INDEX IX_BOUND on [DESC]
 
 

CREATE NONCLUSTERED INDEX [IX_BOUND] ON [dbo].[DESC]
(
	[BoundDescId] ASC
)
INCLUDE ( 	[DescId],
	[Field]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
 


