D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eCatalog.css ..\eCatalog.min.css
move D:\eudonetXRM\XRM\themes\default\css\eCatalog.min.css d:\publish\xrm\themes\default\css\eCatalog.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eActions.css ..\eActions.min.css
move D:\eudonetXRM\XRM\themes\default\css\eActions.min.css d:\publish\xrm\themes\default\css\eActions.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eAdrCheck.css ..\eAdrCheck.min.css
move D:\eudonetXRM\XRM\themes\default\css\eAdrCheck.min.css d:\publish\xrm\themes\default\css\eAdrCheck.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eAvatar.css ..\eAvatar.min.css
move D:\eudonetXRM\XRM\themes\default\css\eAvatar.min.css d:\publish\xrm\themes\default\css\eAvatar.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eButtons.css ..\eButtons.min.css
move D:\eudonetXRM\XRM\themes\default\css\eButtons.min.css d:\publish\xrm\themes\default\css\eButtons.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eCalendar.css ..\eCalendar.min.css
move D:\eudonetXRM\XRM\themes\default\css\eCalendar.min.css d:\publish\xrm\themes\default\css\eCalendar.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eCatalog.css ..\eCatalog.min.css
move D:\eudonetXRM\XRM\themes\default\css\eCatalog.min.css d:\publish\xrm\themes\default\css\eCatalog.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eContextMenu.css ..\eContextMenu.min.css
move D:\eudonetXRM\XRM\themes\default\css\eContextMenu.min.css d:\publish\xrm\themes\default\css\eContextMenu.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eControl.css ..\eControl.min.css
move D:\eudonetXRM\XRM\themes\default\css\eControl.min.css d:\publish\xrm\themes\default\css\eControl.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eEditFile.css ..\eEditFile.min.css
move D:\eudonetXRM\XRM\themes\default\css\eEditFile.min.css d:\publish\xrm\themes\default\css\eEditFile.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eFieldsSelect.css ..\eFieldsSelect.min.css
move D:\eudonetXRM\XRM\themes\default\css\eFieldsSelect.min.css d:\publish\xrm\themes\default\css\eFieldsSelect.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eFile.css ..\eFile.min.css
move D:\eudonetXRM\XRM\themes\default\css\eFile.min.css d:\publish\xrm\themes\default\css\eFile.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eFilterList.css ..\eFilterList.min.css
move D:\eudonetXRM\XRM\themes\default\css\eFilterList.min.css d:\publish\xrm\themes\default\css\eFilterList.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eFilterWizard.css ..\eFilterWizard.min.css
move D:\eudonetXRM\XRM\themes\default\css\eFilterWizard.min.css d:\publish\xrm\themes\default\css\eFilterWizard.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eFinder.css ..\eFinder.min.css
move D:\eudonetXRM\XRM\themes\default\css\eFinder.min.css d:\publish\xrm\themes\default\css\eFinder.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eForgotPwd.css ..\eForgotPwd.min.css
move D:\eudonetXRM\XRM\themes\default\css\eForgotPwd.min.css d:\publish\xrm\themes\default\css\eForgotPwd.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eHomepage.css ..\eHomepage.min.css
move D:\eudonetXRM\XRM\themes\default\css\eHomepage.min.css d:\publish\xrm\themes\default\css\eHomepage.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eIcon.css ..\eIcon.min.css
move D:\eudonetXRM\XRM\themes\default\css\eIcon.min.css d:\publish\xrm\themes\default\css\eIcon.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eList.css ..\eList.min.css
move D:\eudonetXRM\XRM\themes\default\css\eList.min.css d:\publish\xrm\themes\default\css\eList.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eLogin.css ..\eLogin.min.css
move D:\eudonetXRM\XRM\themes\default\css\eLogin.min.css d:\publish\xrm\themes\default\css\eLogin.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eMain.css ..\eMain.min.css
move D:\eudonetXRM\XRM\themes\default\css\eMain.min.css d:\publish\xrm\themes\default\css\eMain.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eMarkedFile.css ..\eMarkedFile.min.css
move D:\eudonetXRM\XRM\themes\default\css\eMarkedFile.min.css d:\publish\xrm\themes\default\css\eMarkedFile.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eMemoEditor.css ..\eMemoEditor.min.css
move D:\eudonetXRM\XRM\themes\default\css\eMemoEditor.min.css d:\publish\xrm\themes\default\css\eMemoEditor.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eModalDialog.css ..\eModalDialog.min.css
move D:\eudonetXRM\XRM\themes\default\css\eModalDialog.min.css d:\publish\xrm\themes\default\css\eModalDialog.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\ePJ.css ..\ePJ.min.css
move D:\eudonetXRM\XRM\themes\default\css\ePJ.min.css d:\publish\xrm\themes\default\css\ePJ.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\ePlanning.css ..\ePlanning.min.css
move D:\eudonetXRM\XRM\themes\default\css\ePlanning.min.css d:\publish\xrm\themes\default\css\ePlanning.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\ePopupFile.css ..\ePopupFile.min.css
vmove D:\eudonetXRM\XRM\themes\default\css\ePopupFile.min.css d:\publish\xrm\themes\default\css\ePopupFile.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eReportWizard.css ..\eReportWizard.min.css
move D:\eudonetXRM\XRM\themes\default\css\eReportWizard.min.css d:\publish\xrm\themes\default\css\eReportWizard.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eSchedule.css ..\eSchedule.min.css
move D:\eudonetXRM\XRM\themes\default\css\eSchedule.min.css d:\publish\xrm\themes\default\css\eSchedule.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eStats.css ..\eStats.min.css
move D:\eudonetXRM\XRM\themes\default\css\eStats.min.css d:\publish\xrm\themes\default\css\eStats.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eStatsPrint.css ..\eStatsPrint.min.css
move D:\eudonetXRM\XRM\themes\default\css\eStatsPrint.min.css d:\publish\xrm\themes\default\css\eStatsPrint.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eTitle.css ..\eTitle.min.css
move D:\eudonetXRM\XRM\themes\default\css\eTitle.min.css d:\publish\xrm\themes\default\css\eTitle.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eTreatment.css ..\eTreatment.min.css
move D:\eudonetXRM\XRM\themes\default\css\eTreatment.min.css d:\publish\xrm\themes\default\css\eTreatment.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eVCard.css ..\eVCard.min.css
move D:\eudonetXRM\XRM\themes\default\css\eVCard.min.css d:\publish\xrm\themes\default\css\eVCard.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\eWizard.css ..\eWizard.min.css
move D:\eudonetXRM\XRM\themes\default\css\eWizard.min.css d:\publish\xrm\themes\default\css\eWizard.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\ie7-styles.css ..\ie7-styles.min.css
move D:\eudonetXRM\XRM\themes\default\css\ie7-styles.min.css d:\publish\xrm\themes\default\css\ie7-styles.css
D:\eudonetXRM\XRM\themes\default\css\CSSmin\cssmin.exe ..\ie8-styles.css ..\ie8-styles.min.css
move D:\eudonetXRM\XRM\themes\default\css\ie8-styles.min.css d:\publish\xrm\themes\default\css\ie8-styles.css
