SET NOCOUNT ON

IF NOT EXISTS (select 1
			from SYS.indexes
			where name = 'IX_FILEDATA_UNIQUE_UID' AND OBJECT_NAME(object_id) = 'FILEDATA')
BEGIN
	CREATE UNIQUE NONCLUSTERED INDEX IX_FILEDATA_UNIQUE_UID ON FILEDATA([UID]) WHERE [UID] IS NOT NULL;
END

SET NOCOUNT OFF