IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE sys.tables.name = 'DESCADV')
BEGIN
	CREATE TABLE [dbo].[DESCADV] (
		[Id] [int] IDENTITY(1,1) NOT NULL,
		[DescId] [numeric](18, 0) NOT NULL,
		[Parameter] [varchar](200) NOT NULL,
		[Value] [nvarchar](max) NULL,
		[Category] [int] NULL,
	 CONSTRAINT [PK_DESCADV] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
	
	ALTER TABLE [dbo].[DESCADV] WITH CHECK ADD  CONSTRAINT [FK_DESCADV_DESC] FOREIGN KEY([DescId]) REFERENCES [dbo].[DESC] ([DescId]) ON DELETE CASCADE
	ALTER TABLE [dbo].[DESCADV] CHECK CONSTRAINT [FK_DESCADV_DESC]
END