USE EUDOTRAIT
IF NOT EXISTS (SELECT * FROM sys.tables tab WHERE tab.name = 'SERVERCONFIG' AND tab.type ='U' )
BEGIN
CREATE TABLE [dbo].[SERVERCONFIG](
	[Id] [int] IDENTITY(1,1) NOT NULL, 
	[Parameter] [varchar](200) NOT NULL, 
	[Value] [varchar](MAX) NULL, 
	[Category] [int] NULL,
CONSTRAINT [PK_SERVERCONFIG] PRIMARY KEY CLUSTERED ( [Id] ASC ) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY] ) 
ON [PRIMARY]
END

IF NOT EXISTS (SELECT * FROM [dbo].[SERVERCONFIG] WHERE [Parameter] = 'DKIM_SIGN_ENABLED')
BEGIN
INSERT INTO [dbo].[SERVERCONFIG] (Parameter, Value, Category) Values ('DKIM_SIGN_ENABLED', '0', NULL)
END
IF NOT EXISTS (SELECT * FROM [dbo].[SERVERCONFIG] WHERE [Parameter] = 'DKIM_DOMAIN')
BEGIN
INSERT INTO [dbo].[SERVERCONFIG] (Parameter, Value, Category) Values ('DKIM_DOMAIN', '', NULL)
END
IF NOT EXISTS (SELECT * FROM [dbo].[SERVERCONFIG] WHERE [Parameter] = 'DKIM_PRIVATE_RSA_KEY')
BEGIN
INSERT INTO [dbo].[SERVERCONFIG] (Parameter, Value, Category) Values ('DKIM_PRIVATE_RSA_KEY', '', NULL)
END
IF NOT EXISTS (SELECT * FROM [dbo].[SERVERCONFIG] WHERE [Parameter] = 'DKIM_SELECTOR')
BEGIN
INSERT INTO [dbo].[SERVERCONFIG] (Parameter, Value, Category) Values ('DKIM_SELECTOR', '', NULL)
END