 if EXISTS (SELECT * FROM sys.indexes WHERE name='IX_CODE' AND object_id = OBJECT_ID('EXTENSION'))
	DROP INDEX [IX_CODE] on EXTENSION
 
 

ALTER TABLE extension alter column EXTENSIONCODE varchar(255) not null


CREATE NONCLUSTERED INDEX [IX_CODE] ON [dbo].[EXTENSION]
(
              [EXTENSIONTYPE] ASC,
              [EXTENSIONCODE] ASC,
              [EXTENSIONUSERID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
 


 