const eFakeRel = [
    {
        "TargetTab": 200,
        "TargetTabLabel": "Contact",
        "IsMiniFileEnabled": true,
        "DescId": 201,
        "PosX": 1,
        "PosY": 14,
        "DispOrder": 37,
        "Colspan": 1,
        "Rowspan": 1,
        "Label": "Relation contact",
        "Format": 9,
        "ToolTipText": "",
        "ValueColor": "",
        "StyleForeColor": "",
        "BackgroundColor": "",
        "Bold": false,
        "Italic": false,
        "Flat": false,
        "Underline": false,
        "LabelHidden": false,
        "Width": 0,
        "IsSortable": false,
        "SortOrder": -1,
        "IsFiltrable": false,
        "IsComputable": false,
        "IsInRules": true,
        "FldFormat": 1,
        "MaxLength": 0
    }, {
        "TargetTab": 300,
        "TargetTabLabel": "Sociétés",
        "IsMiniFileEnabled": true,
        "DescId": 301,
        "PosX": 2,
        "PosY": 19,
        "DispOrder": 44,
        "Colspan": 1,
        "Rowspan": 1,
        "Label": "Relation société",
        "Format": 9,
        "ToolTipText": "",
        "ValueColor": "",
        "StyleForeColor": "",
        "BackgroundColor": "",
        "Bold": false,
        "Italic": false,
        "Flat": false,
        "Underline": false,
        "LabelHidden": false,
        "Width": 0,
        "IsSortable": false,
        "SortOrder": -1,
        "IsFiltrable": false,
        "IsComputable": false,
        "IsInRules": true,
        "FldFormat": 1,
        "MaxLength": 0
    }, {
        "TargetTab": 4000,
        "TargetTabLabel": "Contrats",
        "IsMiniFileEnabled": true,
        "DescId": 4001,
        "PosX": 0,
        "PosY": 2,
        "DispOrder": 5,
        "Colspan": 1,
        "Rowspan": 1,
        "Label": "Contrats",
        "Format": 9,
        "ToolTipText": "",
        "ValueColor": "",
        "StyleForeColor": "",
        "BackgroundColor": "",
        "Bold": false,
        "Italic": false,
        "Flat": false,
        "Underline": false,
        "LabelHidden": false,
        "Width": 0,
        "IsSortable": false,
        "SortOrder": -1,
        "IsFiltrable": false,
        "IsComputable": false,
        "IsInRules": false,
        "FldFormat": 29,
        "MaxLength": 0
    }
];


export { eFakeRel };