
UPDATE [USER] SET [PASSWORD_POLICIES_ALGO] =
	CASE 
		WHEN  ISNULL(EncryptPassword,'') = '' then '0'
		WHEN len(ISNULL(EncryptPassword,'') )= 32 then '1'
		WHEN ISNULL(PASSWORD_POLICIES_ALGO,'') = 'MD5' then '1'
		WHEN ISNULL(PASSWORD_POLICIES_ALGO,'') = 'ARGON2'then '2'
		WHEN ISNULL(PASSWORD_POLICIES_ALGO,'') = 'NONE'then '0'
	END
WHERE [PASSWORD_POLICIES_ALGO] IS NULL OR ISNUMERIC(PASSWORD_POLICIES_ALGO) = 0