INSERT INTO CONFIGADV(Parameter,VALUE,Category)
SELECT 'PASSWORD_POLICIES_ALGO','1',0
WHERE NOT EXISTS (SELECT 1 FROM CONFIGADV WHERE Parameter='PASSWORD_POLICIES_ALGO')

UPDATE [CONFIGADV] SET 
	[VALUE] = 
		CASE 
			WHEN [VALUE] = 'MD5' THEN 1
			WHEN [VALUE] = 'ARGON2' THEN 2
			ELSE 1
		END
	
WHERE Parameter='PASSWORD_POLICIES_ALGO' AND ISNUMERIC(VALUE) = 0 
